// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtrYFQ-ALH9AI_l8sJJKyKMfmeaS3oip8',
    appId: '1:33703602688:web:937ce52cc7cddd3999c6e5',
    messagingSenderId: '33703602688',
    projectId: 'financialadvisorapp-4e1e0',
    authDomain: 'financialadvisorapp-4e1e0.firebaseapp.com',
    storageBucket: 'financialadvisorapp-4e1e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHq80fRgcsudEE0sVQPzSlPShkwxZRz14',
    appId: '1:33703602688:android:f98d8dc3b50a142c99c6e5',
    messagingSenderId: '33703602688',
    projectId: 'financialadvisorapp-4e1e0',
    storageBucket: 'financialadvisorapp-4e1e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD791YmfrBky8y0b6ff0bzLU0MU4padfs0',
    appId: '1:33703602688:ios:c390bdc0d4ca028899c6e5',
    messagingSenderId: '33703602688',
    projectId: 'financialadvisorapp-4e1e0',
    storageBucket: 'financialadvisorapp-4e1e0.firebasestorage.app',
    iosBundleId: 'com.example.financialAdvisorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD791YmfrBky8y0b6ff0bzLU0MU4padfs0',
    appId: '1:33703602688:ios:c390bdc0d4ca028899c6e5',
    messagingSenderId: '33703602688',
    projectId: 'financialadvisorapp-4e1e0',
    storageBucket: 'financialadvisorapp-4e1e0.firebasestorage.app',
    iosBundleId: 'com.example.financialAdvisorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtrYFQ-ALH9AI_l8sJJKyKMfmeaS3oip8',
    appId: '1:33703602688:web:ccd9538b599c3a9199c6e5',
    messagingSenderId: '33703602688',
    projectId: 'financialadvisorapp-4e1e0',
    authDomain: 'financialadvisorapp-4e1e0.firebaseapp.com',
    storageBucket: 'financialadvisorapp-4e1e0.firebasestorage.app',
  );
}
